# docker-compose.yml
version: '3'
services:
  composer:
    image: composer:latest
    volumes:
      - .:/app
    entrypoint: ['composer', '--ignore-platform-reqs']
  php:
    build:
      context: .
      dockerfile: php.dockerfile
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - mongodb
      - mysql

  mysql:
    image: mysql:5.7.29
    container_name: mysql
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: db_app
      MYSQL_ROOT_PASSWORD: p0epsteen

  mongodb:
    image : mongo
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: p0epsteen
    ports:
      - 27017:27017
