# docker-compose.yml
version: '3'
services:
  composer:
    image: composer:latest
    environment:
      - COMPOSER_CACHE_DIR=/app/.cache/composer
    volumes:
      - .:/app
    depends_on:
      - php
    entrypoint: ['composer', '--ignore-platform-reqs']
  php:
    build:
      context: .
      dockerfile: php.dockerfile
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - mongodb
    entrypoint: ['vendor/bin/phpunit']

  mongodb:
    image : mongo
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: p0epsteen
    ports:
      - 27017:27017
